import http from "node:http";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { IndependentCognitiveEngine, CognitiveStateStore, SelfModelStore } from "./brain/cognitive/index.js";
import { deriveSelfModel } from "./brain/cognitive/self-model.js";
const PORT=Number(process.env.PORT||3000),HOST=process.env.HOST||"0.0.0.0",ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public"),AUTH_TOKEN=process.env.JARVIS_AUTH_TOKEN||"";
const store=new CognitiveStateStore(),self=new SelfModelStore(),engine=new IndependentCognitiveEngine();
function json(res,status,body){const d=JSON.stringify(body);res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":process.env.JARVIS_CORS_ORIGIN||"*","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET, POST, OPTIONS"});res.end(d)}
function auth(req){return !AUTH_TOKEN||req.headers.authorization===`Bearer ${AUTH_TOKEN}`}
async function body(req){let s="";for await(const c of req)s+=c;return JSON.parse(s||"{}")}
async function observe(req,res){if(!auth(req))return json(res,401,{error:"Unauthorized"});const b=await body(req),id=String(b.subjectId||"default"),o=String(b.observation||b.event||"").trim();if(!o)return json(res,400,{error:"observation is required"});const c=engine.evaluate({previousState:store.get(id),observations:[{content:o}],context:{subjectId:id,selfModel:self.get(id)}});store.set(id,c);const sm=self.set(id,deriveSelfModel(c,self.get(id)));return json(res,200,{ok:true,observation:o,cognitiveState:c,selfModel:sm})}
const server=http.createServer(async(req,res)=>{try{if(req.method==="OPTIONS")return json(res,204,{});const u=new URL(req.url,"http://localhost");if(req.method==="GET"&&u.pathname==="/"){const f=path.join(ROOT,"index.html");if(fs.existsSync(f)){res.writeHead(200,{"Content-Type":"text/html; charset=utf-8"});return fs.createReadStream(f).pipe(res)}return json(res,200,{ok:true,name:"Jarvis Beta",status:"online",cognitiveLab:true,voice:false})}if(req.method==="GET"&&u.pathname==="/health")return json(res,200,{ok:true,service:"jarvis-server",cognitiveLab:true});if(req.method==="GET"&&u.pathname==="/v1/cognitive/state"){const id=u.searchParams.get("subjectId")||"default";return json(res,200,{ok:true,cognitiveState:store.get(id),selfModel:self.get(id)})}if(req.method==="POST"&&u.pathname==="/v1/cognitive/observe")return observe(req,res);if(req.method==="POST"&&u.pathname==="/v1/cognitive/reset"){if(!auth(req))return json(res,401,{error:"Unauthorized"});const b=await body(req),id=String(b.subjectId||"default");store.clear(id);self.clear(id);return json(res,200,{ok:true,subjectId:id})}return json(res,404,{error:"Not found"})}catch(e){return json(res,500,{error:e.message})}});
server.listen(PORT,HOST,()=>console.log(`Jarvis server listening on http://${HOST}:${PORT}`));