const state={events:[],cognitive:null,self:null};
const $=id=>document.getElementById(id);
const storageKey="jarvisLabApi";
const config=JSON.parse(localStorage.getItem(storageKey)||"{}");
const levelValue={low:.25,medium:.55,high:.85};
const pct=v=>Math.round((typeof v==="number"?v:(levelValue[v]??0))*100)+"%";
const esc=s=>String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
function saveConfig(){config.apiBase=$("apiBase").value.trim().replace(/\/$/,"");config.token=$("token").value.trim();config.subjectId=$("subjectId").value.trim()||"luiz";localStorage.setItem(storageKey,JSON.stringify(config));$("configStatus").textContent=config.apiBase&&config.token?"CONFIGURED":"MISSING CONFIG";}
function headers(){return{"Content-Type":"application/json","Authorization":"Bearer "+config.token};}
function render(){const c=state.cognitive||{};$("concern").textContent=pct(c.concern);$("uncertainty").textContent=pct(c.uncertainty);$("curiosity").textContent=pct(c.curiosity);$("confidence").textContent=pct(c.confidence);$("action").textContent=c.recommendedAction||"—";$("reason").textContent=c.reason||"Nenhuma avaliação ainda.";$("self").textContent=JSON.stringify(state.self||{},null,2);$("hypotheses").innerHTML=(c.hypotheses||[]).map(h=>"<div class=\"hyp\"><b>"+esc(h.statement)+"</b><span>"+esc(h.confidence)+"</span><small>+ "+esc((h.evidenceFor||[]).join("; ")||"—")+"<br>− "+esc((h.evidenceAgainst||[]).join("; ")||"—")+"</small></div>").join("")||"<div>Nenhuma hipótese.</div>";$("timeline").innerHTML=state.events.slice().reverse().map(e=>"<div class=\"event\"><small>"+esc(e.time)+"</small><br>"+esc(e.text)+"<br><small>ação: "+esc(e.action||"—")+" · incerteza: "+esc(pct(e.uncertainty))+"</small></div>").join("")||"<div class=\"event\">Nenhum evento observado ainda.</div>";$("status").textContent=state.cognitive?"LIVE":"READY";}
async function observe(text){if(!text.trim())return;saveConfig();if(!config.apiBase||!config.token){$("status").textContent="CONFIG REQUIRED";return;}$("status").textContent="THINKING";try{const r=await fetch(config.apiBase+"/v1/cognitive/observe",{method:"POST",headers:headers(),body:JSON.stringify({subjectId:config.subjectId,observation:text,type:"lab_observation"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"HTTP "+r.status);state.cognitive=d.cognitiveState;state.self=d.selfModel;state.events.push({time:new Date().toLocaleTimeString("pt-BR"),text,action:d.cognitiveState.recommendedAction,uncertainty:d.cognitiveState.uncertainty});$("event").value="";render();}catch(e){$("status").textContent="ERROR";$("reason").textContent=e.message;}}
async function loadState(){saveConfig();if(!config.apiBase||!config.token)return;try{const r=await fetch(config.apiBase+"/v1/cognitive/state?subjectId="+encodeURIComponent(config.subjectId),{headers:headers()});if(!r.ok)return;const d=await r.json();state.cognitive=d.cognitiveState;state.self=d.selfModel;render();}catch{}}
async function resetLab(){saveConfig();if(!config.apiBase||!config.token)return;await fetch(config.apiBase+"/v1/cognitive/reset",{method:"POST",headers:headers(),body:JSON.stringify({subjectId:config.subjectId})});state.events=[];state.cognitive=null;state.self=null;render();}
async function runExperiment(){for(const e of ["O usuário normalmente interage neste período.","O usuário não apareceu no padrão esperado.","O dispositivo continua online, mas não há nova interação.","Nenhuma explicação suficiente está disponível.","O usuário voltou e explicou que estava ocupado."]){await observe(e);await new Promise(r=>setTimeout(r,250));}}
$("apiBase").value=config.apiBase||"";$("token").value=config.token||"";$("subjectId").value=config.subjectId||"luiz";$("saveConfig").onclick=saveConfig;$("observe").onclick=()=>observe($("event").value);$("experiment").onclick=runExperiment;$("reset").onclick=resetLab;$("configStatus").textContent=config.apiBase&&config.token?"CONFIGURED":"MISSING CONFIG";render();loadState();